AndreyLubkin/Classwork/ClassWork24/ClassWork24/Models/ErrorViewModel.cs
using System;

namespace ClassWork24.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AndreyLubkin/Classwork/ClassWork24/ClassWork24/Controllers/FsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ClassWork24.Controllers {
    public class FsController :Controller {
        public IActionResult FsInfo() {
            return View();
        }

        public IActionResult DrivesInfo() {
            return View();
        }

        public IActionResult Directories() {
            return View();
        }

        public IActionResult DeleteDirectories() {
            string userFolder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            string[] customFolder = new string[] { userFolder,"Code","NewFolder" };

            string dir = System.IO.Path.Combine(customFolder);
            System.IO.Directory.Delete(dir, recursive: true);

            return RedirectToAction("Directories");
        }
    }
}

AndreyLubkin/Classwork/ClassWork24/ClassWork24/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ClassWork24.Models;

namespace ClassWork24.Controllers {
    public class HomeController :Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AndreyLubkin/Classwork/ClassWork24/ClassWork24/Views/Fs/Directories.cshtml
@using System
@using System.IO


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Directories</title>
</head>
<body>
    @{
        string userFolder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
        string[] customFolder = new string[] {
            userFolder,"Code","NewFolder"
        };

        string dir = System.IO.Path.Combine(customFolder);
    }
    Does folder exist? @Directory.Exists(dir)
    @{
        Directory.CreateDirectory(dir);
    }
    Does folder exist? @Directory.Exists(dir)

    <p>@Html.ActionLink("DeleteDirectories","DeleteDirectories","Fs")<p/>
</body>
</html>

AndreyLubkin/Classwork/ClassWork24/ClassWork24/Views/Fs/DrivesInfo.cshtml
@using System.IO;

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DrivesInfo</title>
    <style>
        table,th,td{
            border: 1px solid black;
        }
    </style>
</head>
<body>
    @foreach(DriveInfo item in DriveInfo.GetDrives()) {
        @if(item.IsReady) {
            <table style="border-collapse: collapse; border: 1px solid black">
                <tr>
                    <th>Name</th>
                    <th>VolumeLabel</th>
                    <th>TotalSize</th>
                    <th>TotalFreeSpace</th>
                </tr>
                <tr>
                    <td>@item.Name</td>
                    <td>@item.VolumeLabel</td>

                    <td>@item.TotalSize</td>
                    <td>@item.TotalFreeSpace</td>

                </tr>
            </table>
        }
    }
</body>
</html>

AndreyLubkin/Classwork/ClassWork24/ClassWork24/Views/Fs/FsInfo.cshtml
@using System

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FsInfo</title>
</head>
<body>
    <p>
        Path Separator: @System.IO.Path.PathSeparator<br />
        Directory Separator Char: @System.IO.Path.DirectorySeparatorChar<br />
        Current Directory: @System.Environment.CurrentDirectory<br />
        System Directory: @System.Environment.SystemDirectory<br />
        System Directory: @System.Environment.SystemDirectory<br />
        Temp Directory: @System.IO.Path.GetTempPath()<br />
        ApplicationData: @Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)<br />
    </p>
</body>
</html>

AndreyLubkin/Classwork/ClassWork24/ClassWork24/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>@Html.ActionLink("FsInfo", "FsInfo", "Fs")</p>
        <p>@Html.ActionLink("DrivesInfo", "DrivesInfo", "Fs")</p>
        <p>@Html.ActionLink("Directories", "Directories", "Fs")</p>


    </div>

AndreyLubkin/Classwork/ClassWork24/ClassWork24/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassWork24</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClassWork24</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ClassWork24 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>